[versions]
spatialBom = "6.1.9"
agp = "8.7.3"
kotlin = "2.0.21"
coreKtx = "1.16.0"
androidxLifecycle = "2.10.0"
activityCompose = "1.10.1"
annotation = "1.9.1"
appcompat = "1.7.1"

[libraries]
spatial-bom = { module = "com.pico.spatial:bom", version.ref = "spatialBom" }
spatial-foundation = { group = "com.pico.spatial.foundation", name = "foundation" }
spatial-core = { group = "com.pico.spatial.core", name = "core" }
spatial-tracking = { group = "com.pico.spatial.tracking", name = "tracking" }
spatial-sense = { group = "com.pico.spatial.sense", name = "sense" }
spatial-ui-platform = { group = "com.pico.spatial.ui", name = "platform" }
spatial-ui-design = { group = "com.pico.spatial.ui", name = "design" }
spatial-ui-foundation = { group = "com.pico.spatial.ui", name = "foundation" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose-android", version.ref = "androidxLifecycle" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
